INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (3, 'Acute nasopharyngitis [common cold]', 'J00', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (4, 'Acute upper respiratory infection, unspecified', 'J06.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (5, 'Myalgia', 'M79.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (6, 'Fever, unspecified', 'R50.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (7, 'Dyspepsia', 'K30', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (8, 'Headache (Cephalgia)', 'R51', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (9, 'Low back pain', 'M54.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (10, 'Diarrhoea and gastroenteritis of presumed infectious origin', 'A09', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (11, 'Other surgical follow-up care', 'Z48', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (12, 'Typhoid fever', 'A01.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (13, 'Acute pharyngitis, unspecified', 'J02.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (14, 'Functional diarrhoea', 'K59.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (15, 'Dengue fever [classical dengue]', 'A90', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (16, 'Cough', 'R05', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (17, 'General examination and investigation of persons without complaint', 'Z00', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (18, 'Conjunctivitis, unspecified', 'H10.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (19, 'Other and unspecified abdominal pain', 'R10.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (20, 'Nausea and vomiting', 'R11', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (21, 'Pulpitis', 'K04.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (22, 'Acute tonsillitis, unspecified', 'J03.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (23, 'Dizziness and giddiness', 'R42', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (24, 'Essential (primary) hypertension', 'I10', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (25, 'Superficial injury of unspecified body region', 'T14.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (26, 'Supervision of normal pregnancy', 'Z34', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (27, 'Dermatitis, unspecified', 'L30.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (28, 'Urinary tract infection, site not specified', 'N39.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (29, 'NEKROSIS PULPA/GANGREN PULPA', 'K04.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (30, 'Malaise and fatigue', 'R53', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (31, 'Tension-type headache', 'G44.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (32, 'Dysmenorrhoea, unspecified', 'N94.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (33, 'Retained dental root', 'K08.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (34, 'Other peripheral vertigo', 'H81.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (35, 'Muscle strain', 'M62.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (36, 'Pure hypercholesterolaemia', 'E78.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (37, 'Dengue haemorrhagic fever', 'A91', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (38, 'Typhoid and paratyphoid fevers', 'A01', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (39, 'Cutaneous abscess, furuncle and carbuncle, unspecified', 'L02.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (40, 'Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease', 'E79.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (41, 'Chest pain, unspecified', 'R07.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (42, 'Surgical follow-up care, unspecified', 'Z48.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (43, 'Open wound of unspecified body region', 'T14.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (44, 'Hordeolum and other deep inflammation of eyelid', 'H00.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (45, 'Otitis externa, unspecified', 'H60.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (46, 'Impacted teeth', 'K01.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (47, 'Necrosis of pulp', 'K04.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (48, 'Chronic gingivitis', 'K05.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (49, 'Impacted cerumen', 'H61.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (50, 'Benign paroxysmal vertigo', 'H81.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (51, 'Asthma, unspecified', 'J45.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (52, 'Influenza with other manifestations, virus not identified', 'J11.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (53, 'Acute gingivitis', 'K05.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (54, 'Pain in joint', 'M25.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (55, 'Mild hyperemesis gravidarum', 'O21.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (56, 'Gastro-oesophageal reflux disease without oesophagitis', 'K21.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (57, 'General Adult Medical Examination', 'Z00.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (58, 'Constipation', 'K59.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (59, 'Allergic urticaria', 'L50.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (60, 'Headache', 'R51', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (61, 'Urinary calculus, unspecified', 'N20.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (62, 'General Weakness', 'R53.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (63, 'Influenza with other respiratory manifestations, virus not', 'J11.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (64, 'Sprain and strain of ankle', 'S93.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (65, 'Acute laryngopharyngitis', 'J06.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (66, 'Bacterial infection, unspecified', 'A49.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (67, 'Other forms of stomatitis', 'K12.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (68, 'Other gastroenteritis and colitis of infectious and unspecified origin ', 'A09', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (69, 'Internal haemorrhoids without complication', 'I84.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (70, 'Bronchopneumonia, unspecified', 'J18.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (71, 'Cutaneous abscess, furuncle and carbuncle of other sites', 'L02.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (72, 'Non-insulin-dependent diabetes mellitus', 'E11', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (73, 'Varicella [chickenpox]', 'B01', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (74, 'Allergy, unspecified', 'T78.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (75, 'Fever with chills', 'R50.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (76, 'Gout, unspecified', 'M10.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (77, 'ABSES PERIAPIKAL WITHOUT SINUS', 'K04.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (78, 'Pyoderma', 'L08.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (79, 'Foreign body in cornea', 'T15.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (80, 'Q fever', 'A78', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (81, 'Primary dysmenorrhoea', 'N94.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (82, 'Thrombocytopenia, unspecified', 'D69.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (83, 'Acute conjunctivitis, unspecified', 'H10.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (84, 'Internal thrombosed haemorrhoids', 'I84.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (85, 'Periapical Abscess Without Sinus', 'K04.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (86, 'Pain, unspecified', 'R52.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (87, 'Abdominal pregnancy', 'O00.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (88, 'Influenza with other manifestations, influenza virus identified', 'J10.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (89, 'Otitis media, unspecified', 'H66.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (90, 'Urticaria, unspecified', 'L50.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (91, 'Migraine without aura [common migraine]', 'G43.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (92, 'Arthritis, unspecified', 'M13.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (93, 'Measles', 'B05', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (94, 'Tinea corporis', 'B35.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (95, 'Other otitis externa', 'H60.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (96, 'Scabies', 'B86', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (97, 'Miliaria, unspecified', 'L74.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (98, 'Acute abdomen', 'R10.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (99, 'Pneumonia, unspecified', 'J18.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (100, 'Orchitis, epididymitis and epididymo-orchitis without abscess', 'N45.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (101, 'Other chest pain', 'R07.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (102, 'Migraine, unspecified', 'G43.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (103, 'Pruritus, unspecified', 'L29.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (104, 'General medical examination', 'Z00.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (105, 'Anaemia, unspecified', 'D64.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (106, 'Cervicalgia', 'M54.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (107, 'Other acute gastritis', 'K29.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (108, 'Cramp and spasm', 'R25.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (109, 'Other conjunctivitis', 'H10.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (110, 'General examination and investigation of persons without complaint and reported diagnosis', 'Z00', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (111, 'Noninfective gastroenteritis and colitis, unspecified', 'K52.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (112, 'Acute serous otitis media', 'H65.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (113, 'Coronavirus infection, Unspecified Site', 'B34.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (114, 'Atopic dermatitis, unspecified', 'L20.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (115, 'Allergic rhinitis, unspecified', 'J30.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (116, 'Open wound of finger(s) without damage to nail', 'S61.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (117, 'Fracture of other finger', 'S62.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (118, 'Influenza with other respiratory manifestations, influenza virus', 'J10.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (119, 'Respiratory tuberculosis, bacteriologically and histologically confirmed', 'A15', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (120, 'Allergic contact dermatitis, unspecified cause', 'L23.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (121, 'Second degree hemorrhoids', 'K64.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (122, 'Other gastritis', 'K29.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (123, 'Tinea pedis', 'B35.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (124, 'Sciatica', 'M54.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (125, 'Myopia', 'H52.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (126, 'Acute pharyngitis', 'J02', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (127, 'Dyspnoea', 'R06.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (128, 'Hemorrhoids and perianal venous thrombosis', 'K64', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (129, 'Dental caries, unspecified', 'K02.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (130, 'Epistaxis', 'R04.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (131, 'Acute bronchitis, unspecified', 'J20.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (132, 'Febrile convulsions', 'R56.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (133, 'KARIES DENTIN', 'K02.62', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (134, 'Epidemic vertigo', 'A88.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (135, 'Unilateral or unspecified inguinal hernia, without obstruction or', 'K40.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (136, 'Acute hepatitis B', 'B16', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (137, 'Haemophilus influenzae infection, unspecified', 'A49.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (138, 'Irritable bowel syndrome with diarrhoea', 'K58.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (139, 'Ingrowing nail', 'L60.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (140, 'Chronic periodontitis', 'K05.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (141, 'Cutaneous abscess, furuncle and carbuncle of limb', 'L02.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (142, 'Tinea cruris', 'B35.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (143, 'Elevation of levels of transaminase and lactic acid dehydrogenase [LDH]', 'R74.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (144, 'Mumps', 'B26', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (145, 'Disorder of white blood cells, unspecified', 'D72.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (146, 'Chronic tonsillitis', 'J35.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (147, 'External haemorrhoids without complication', 'I84.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (148, 'First degree hemorrhoids', 'K64.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (149, 'Zoster [herpes zoster]', 'B02.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (150, 'Open wound of finger(s) with damage to nail', 'S61.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (151, 'Pterygium', 'H11.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (152, 'Other anaemias', 'D64', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (153, 'Acute tonsillitis', 'J03', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (154, 'Hyperlipidaemia, unspecified', 'E78.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (155, 'Sprain and strain of other and unspecified parts of knee', 'S83.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (156, 'Gastritis, unspecified', 'K29.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (157, 'Irritant contact dermatitis, unspecified cause', 'L24.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (158, 'Insulin-dependent diabetes mellitus', 'E10', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (159, 'Cutaneous abscess, furuncle and carbuncle of face', 'L02.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (160, 'Third degree hemorrhoids', 'K64.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (161, 'Cutaneous abscess, furuncle and carbuncle of buttock', 'L02.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (162, 'Foreign body in ear', 'T16', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (163, 'Polymyalgia rheumatica', 'M35.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (164, 'Otalgia', 'H92.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (165, 'Viral infection, unspecified', 'B34.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (166, 'Open wound of lower leg, part unspecified', 'S81.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (167, 'Calculus of kidney', 'N20.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (168, 'Other atopic dermatitis', 'L20.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (169, 'Unspecified hemorrhoids', 'K64.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (170, 'Other acute conjunctivitis', 'H10.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (171, 'Polyarthritis, unspecified', 'M13.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (172, 'Impetigo [any organism] [any site]', 'L01.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (173, 'Multisystem inflamatory syndrome associated with COVID-19, Unspecified (Post Covid-19)', 'U10.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (174, 'Vertigo of central origin', 'H81.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (175, 'Anxiety disorder, unspecified', 'F41.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (176, 'Cellulitis of finger and toe', 'L03.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (177, 'Tuberculosis of lung, confirmed by unspecified means', 'A15.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (178, 'Other anxiety disorders', 'F41', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (179, 'Nail disorder, unspecified', 'L60.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (180, 'Disorders of initiating and maintaining sleep [insomnias]', 'G47.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (181, 'Gastroenteritis and colitis of unspecified origin', 'A09.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (182, 'Spondylosis, unspecified', 'M47.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (183, 'Acute lymphadenitis, unspecified', 'L04.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (184, 'Other specified dermatitis', 'L30.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (185, 'Connective and other soft tissue, unspecified', 'D21.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (186, 'Idiopathic urticaria', 'L50.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (187, 'Gastro-oesophageal reflux disease with oesophagitis', 'K21.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (188, 'Iron deficiency anaemia', 'D50', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (189, 'Other benign neoplasms of connective and other soft tissue', 'D21', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (190, 'Superficial injury of lower leg, unspecified', 'S80.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (191, 'Vomiting of pregnancy, unspecified', 'O21.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (192, 'Contusion of thorax', 'S20.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (193, 'Miliaria rubra', 'L74.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (194, 'Sprain and strain of wrist', 'S63.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (195, 'Caries of dentine', 'K02.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (196, 'Dental caries on pit and fissure surface penetrating into dentin', 'K02.52', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (197, 'Sprain and strain of shoulder joint', 'S43.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (198, 'Thyrotoxicosis [hyperthyroidism]', 'E05', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (199, 'Acute appendicitis, unspecified', 'K35.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (200, 'Bacterial infection of unspecified site', 'A49', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (201, 'Paratyphoid fever, unspecified', 'A01.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (202, 'Blepharitis', 'H01.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (203, 'Injury, unspecified', 'T14.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (204, 'PERSISTENSI GIGI SULUNG', 'K00.63', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (205, 'Zoster [herpes zoster]', 'B02', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (206, 'Carpal tunnel syndrome', 'G56.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (207, 'Acute sinusitis, unspecified', 'J01.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (208, 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods', 'W57', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (209, 'Dental caries on smooth surface penetrating into dentin', 'K02.62', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (210, 'Calculus of lower urinary tract, unspecified', 'N21.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (211, 'Viral conjunctivitis', 'B30', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (212, 'Superficial injury of wrist and hand, unspecified', 'S60.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (213, 'Open wound of scalp', 'S01.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (214, 'Bradycardia, unspecified', 'R00.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (215, 'Open wound of other parts of foot', 'S91.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (216, 'Oedema, unspecified', 'R60.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (217, 'Acute suppurative otitis media', 'H66.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (218, 'Contusion of finger(s) with damage to nail', 'S60.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (219, 'Disease of salivary gland, unspecified ( parotitis )', 'K11.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (220, 'Acute Gingivitis, Plaque Induced', 'K05.00', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (221, 'Pityriasis versicolor', 'B36.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (222, 'Haemoptysis', 'R04.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (223, 'Disorder of purine and pyrimidine metabolism, unspecified', 'E79.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (224, 'Allergic contact dermatitis due to other agents', 'L23.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (225, 'Dental examination', 'Z01.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (226, 'Disorders of purine and pyrimidine metabolism', 'E79', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (227, 'Pleural effusion, not elsewhere classified', 'J90', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (228, 'Conjunctival haemorrhage', 'H11.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (229, 'Mucopurulent conjunctivitis', 'H10.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (230, 'Burn of unspecified body region, unspecified degree', 'T30.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (231, 'Fracture of clavicle', 'S42.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (232, 'Supervision of other normal pregnancy', 'Z34.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (233, 'Persistent fever', 'R50.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (234, 'Open wound of other parts of wrist and hand', 'S61.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (235, 'Contusion of knee', 'S80.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (236, 'Disease of upper respiratory tract, unspecified', 'J39.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (237, 'Other lower urinary tract calculus', 'N21.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (238, 'Superficial injury of head, part unspecified', 'S00.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (239, 'Foreign body in conjunctival sac', 'T15.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (240, 'Radiculopathy', 'M54.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (241, 'Cutaneous abscess, furuncle and carbuncle of neck', 'L02.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (242, 'Supervision of normal first pregnancy', 'Z34.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (243, 'Allergic purpura', 'D69.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (244, 'Hidradenitis suppurativa', 'L73.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (245, 'Contusion of finger(s) without damage to nail', 'S60.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (246, 'Other disorders of lacrimal gland', 'H04.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (247, 'Cellulitis, unspecified', 'L03.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (248, 'Other specified arthritis', 'M13.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (249, 'Acute lymphadenitis of face, head and neck', 'L04.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (250, 'Other acute upper respiratory infections of multiple sites', 'J06.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (251, 'Open wound of other parts of lower leg', 'S81.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (252, 'Burn of second degree of wrist and hand', 'T23.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (253, 'Superficial injury of ankle and foot, unspecified', 'S90.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (254, 'ABSES PERIODOTAL', 'K05.21', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (255, 'Contusion of other and unspecified parts of foot', 'S90.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (256, 'Other infective otitis externa', 'H60.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (257, 'Bronchitis, not specified as acute or chronic', 'J40', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (258, 'Sprain and strain of other and unspecified parts of foot', 'S93.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (259, 'Acute upper respiratory infections of multiple and unspecified sites', 'J06', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (260, 'STOMATITIS PSEUDOMEMBRAN AKUT', 'B37.00', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (261, 'Open wound of head, part unspecified', 'S01.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (262, 'Open wound of wrist and hand part, part unspecified', 'S61.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (263, 'Open wound of other parts of head', 'S01.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (264, 'Abscess, furuncle and carbuncle of nose', 'J34.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (265, 'Retained [persistent] primary [deciduous] teeth (IM)', 'K00.63', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (266, 'Other orthopaedic follow-up care', 'Z47', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (267, 'Open wound of knee', 'S81.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (268, 'Neuralgia and neuritis, unspecified', 'M79.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (269, 'Vascular headache, not elsewhere classified', 'G44.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (270, 'Laboratory examination', 'Z01.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (271, 'Other specified surgical follow-up care', 'Z48.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (272, 'Adhesive capsulitis of shoulder', 'M75.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (273, 'Chalazion', 'H00.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (274, 'Unspecified injury of head', 'S09.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (275, 'Bell\'s palsy', 'G51.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (276, 'Haemorrhage in early pregnancy, unspecified', 'O20.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (277, 'Chest pain on breathing', 'R07.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (278, 'Acute otitis externa, noninfective', 'H60.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (279, 'Internal haemorrhoids with other complications', 'I84.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (280, 'Plantar fascial fibromatosis', 'M72.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (281, 'Other disorders of white blood cells', 'D72', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (282, 'Tuberculosis of lung, confirmed by sputum microscopy with or without culture', 'A15.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (283, 'Local infection of skin and subcutaneous tissue, unspecified', 'L08.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (284, 'Multiple superficial injuries, unspecified', 'T00.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (285, 'Burn of second degree of ankle and foot', 'T25.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (286, 'External thrombosed haemorrhoids', 'I84.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (287, 'Acute maxillary sinusitis', 'J01.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (288, 'Pain localized to other parts of lower abdomen', 'R10.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (289, 'Contusion of lower back and pelvis', 'S30.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (290, 'Enlarged lymph nodes, unspecified', 'R59.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (291, 'Syncope and collapse', 'R55', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (292, 'Diaper [napkin] dermatitis', 'L22', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (293, 'Pain in limb', 'M79.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (294, 'Spontaneous abortion - incomplete, without complication', 'O03.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (295, 'Corns and callosities', 'L84', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (296, 'Burn of second degree, body region unspecified', 'T30.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (297, 'Cardiomegaly', 'I51.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (298, 'Other specified disorders of muscle', 'M62.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (299, 'Threatened abortion', 'O20.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (300, 'Other cholelithiasis', 'K80.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (301, 'Allergic contact dermatitis due to other chemical products', 'L23.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (302, 'Perforation of tympanic membrane, unspecified', 'H72.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (303, 'Burn of first degree of wrist and hand', 'T23.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (304, 'Haematemesis', 'K92.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (305, 'Fracture of lower end of radius', 'S52.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (306, 'Contusion of other and unspecified parts of lower leg', 'S80.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (307, 'Other allergic rhinitis', 'J30.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (308, 'Cluster headache syndrome', 'G44.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (309, 'Tinnitus', 'H93.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (310, 'Fracture of other metacarpal bone', 'S62.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (311, 'Syphilis, unspecified', 'A53.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (312, 'Connective and other soft tissue of head, face and neck', 'D21.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (313, 'Contusion of ankle', 'S90.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (314, 'Acute cystitis', 'N30.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (315, 'Human immunodeficiency virus [HIV] disease resulting in infectious and', 'B20', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (316, 'Haemorrhage of anus and rectum', 'K62.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (317, 'Unspecified contact dermatitis, unspecified cause', 'L25.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (318, 'Open wound of eyelid and periocular area', 'S01.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (319, 'Orthopaedic follow-up care, unspecified', 'Z47.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (320, 'Fasciitis, not elsewhere classified', 'M72.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (321, 'Contusion of other parts of wrist and hand', 'S60.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (322, 'Superficial injury of other parts of head', 'S00.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (323, 'Burns involving less than 10% of body surface', 'T31.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (324, 'Chronic sinusitis, unspecified', 'J32.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (325, 'Concussion', 'S06.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (326, 'Irritable bowel syndrome without diarrhoea', 'K58.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (327, 'Lichen simplex chronicus', 'L28.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (328, 'Foreign body on external eye, part unspecified', 'T15.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (329, 'Contusion of shoulder and upper arm', 'S40.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (330, 'Lumbar and other intervertebral disc disorders with radiculopathy', 'M51.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (331, 'Other dental caries', 'K02.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (332, 'Tinea barbae and tinea capitis', 'B35.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (333, 'Irregular menstruation, unspecified', 'N92.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (334, 'Supervision of normal pregnancy, unspecified', 'Z34.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (335, 'Unilateral or unspecified inguinal hernia, with obstruction, without', 'K40.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (336, 'Irritant contact dermatitis due to other chemical products', 'L24.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (337, 'Hyperglycaemia, unspecified', 'R73.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (338, 'Cellulitis of other sites', 'L03.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (339, 'Other hemorrhoids', 'K64.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (340, 'Haemorrhoids', 'I84', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (341, 'Open wound of lip and oral cavity', 'S01.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (342, 'Occupational health examination', 'Z10.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (343, 'Unspecified haematuria', 'R31', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (344, 'Ocular pain', 'H57.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (345, 'Sprain and strain of elbow', 'S53.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (346, 'Abrasion of teeth', 'K03.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (347, 'Abnormal uterine and vaginal bleeding, unspecified', 'N93.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (348, 'Injury of eye and orbit, part unspecified', 'S05.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (349, 'Arthrosis, unspecified', 'M19.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (350, 'Candidal stomatitis', 'B37.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (351, 'Non-insulin-dependent diabetes mellitus without complications', 'E11.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (352, 'Bacterial pneumonia, unspecified', 'J15.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (353, 'Superficial injury of forearm, unspecified', 'S50.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (354, 'Other ill-defined and unspecified causes of mortality', 'R99', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (355, 'Excessive and frequent menstruation with irregular cycle', 'N92.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (356, 'Other pruritus', 'L29.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (357, 'Fracture of tooth', 'S02.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (358, 'Localized enlarged lymph nodes', 'R59.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (359, 'Cutaneous abscess, furuncle and carbuncle of trunk', 'L02.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (360, 'Abnormality of white blood cells, not elsewhere classified', 'R72', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (361, 'Generalized anxiety disorder', 'F41.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (362, 'Soft tissue disorder, unspecified', 'M79.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (363, 'Tinea manuum', 'B35.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (364, 'Other primary disorders of muscles', 'G71.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (365, 'Superficial injury of scalp', 'S00.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (366, 'Dorsalgia, unspecified', 'M54.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (367, 'Rheumatoid arthritis, unspecified', 'M06.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (368, 'Dislocation of shoulder joint', 'S43.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (369, 'Suppurative otitis media, unspecified', 'H66.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (370, 'Other superficial injuries of lower leg', 'S80.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (371, 'Unspecified acute lower respiratory infection', 'J22', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (372, 'Other general examinations', 'Z00.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (373, 'Other chronic suppurative otitis media', 'H66.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (374, 'Influenza due to other identified influenza virus', 'J10', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (375, 'Other migraine', 'G43.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (376, 'Acute pain', 'R52.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (377, 'Unspecified renal colic', 'N23', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (378, 'Chronic serous otitis media', 'H65.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (379, 'Fracture of metatarsal bone', 'S92.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (380, 'Fracture of fibula alone', 'S82.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (381, 'Acute laryngitis', 'J04.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (382, 'KARIES PIT DAN FISSURE MENCAPAI DENTIN', 'K02.52', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (383, 'Follow-up examination after surgery for other conditions', 'Z09.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (384, 'KARIES EMAIL', 'K02.61', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (385, 'Acute tonsillitis due to other specified organisms', 'J03.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (386, 'Keloid scar', 'L91.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (387, 'Other prurigo', 'L28.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (388, 'Spondylolysis', 'M43.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (389, 'Benign lipomatous neoplasm', 'D17', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (390, 'Viral infection of unspecified site', 'B34', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (391, 'Dermatophytosis', 'B35', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (392, 'Unspecified haemorrhoids without complication', 'I84.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (393, 'Benign neoplasm of breast', 'D24', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (394, 'Vasomotor rhinitis', 'J30.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (395, 'Acute myocardial infarction, unspecified', 'I21.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (396, 'Abnormal findings on diagnostic imaging of lung', 'R91', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (397, 'Calculus of ureter', 'N20.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (398, 'Epilepsy, unspecified', 'G40.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (399, 'Haemophilus influenzae infection, unspecified site', 'A49.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (400, 'Other and unspecified convulsions', 'R56.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (401, 'Angina pectoris, unspecified', 'I20.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (402, 'Hearing loss, unspecified', 'H91.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (403, 'Burn of first degree, body region unspecified', 'T30.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (404, 'Irritant contact dermatitis due to other agents', 'L24.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (405, 'Hypoglycaemia, unspecified', 'E16.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (406, 'Caries limited to enamel', 'K02.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (407, 'Monoarthritis, not elsewhere classified', 'M13.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (408, 'Localized swelling, mass and lump, unspecified', 'R22.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (409, 'Excessive and frequent menstruation with regular cycle', 'N92.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (410, 'Burn of first degree of ankle and foot', 'T25.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (411, 'Other and unspecified gastroen teritis and colitis of infectious origin', 'A09.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (412, 'Viral warts', 'B07', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (413, 'Contusion of eyelid and periocular area', 'S00.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (414, 'Other and unspecified hydronephrosis', 'N13.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (415, 'Inflammation of eyelid, unspecified', 'H01.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (416, 'Allergic contact dermatitis due to plants, except food', 'L23.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (417, 'Nummular dermatitis', 'L30.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (418, 'Inflammatory disorders of breast', 'N61', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (419, 'Other urticaria', 'L50.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (420, 'Superficial injury of shoulder and upper arm, unspecified', 'S40.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (421, 'Abnormal results of cardiovascular function studies', 'R94.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (422, 'Traumatic amputation of other single finger (complete)(partial)', 'S68.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (423, 'Disorder of refraction, unspecified', 'H52.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (424, 'Nonsuppurative otitis media, unspecified', 'H65.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (425, 'Localized oedema', 'R60.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (426, 'Cellulitis and abscess of mouth', 'K12.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (427, 'Ganglion', 'M67.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (428, 'Orthostatic hypotension', 'I95.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (429, 'Varicella without complication', 'B01.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (430, 'Fracture of foot, unspecified', 'S92.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (431, 'Antenatal screening, unspecified', 'Z36.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (432, 'Other nail disorders', 'L60.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (433, 'Other specified noninfective gastroenteritis and colitis', 'K52.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (434, 'Burn of second degree of hip and lower limb, except ankle and foot', 'T24.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (435, 'Seborrhoeic dermatitis, unspecified', 'L21.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (436, 'Infective dermatitis', 'L30.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (437, 'Gastrointestinal haemorrhage, unspecified', 'K92.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (438, 'External haemorrhoids with other complications', 'I84.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (439, 'Corneal ulcer', 'H16.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (440, 'Amenorrhoea, unspecified', 'N91.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (441, 'Fourth degree hemorrhoids', 'K64.3', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (442, 'Low vision, one eye', 'H54.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (443, 'Polyneuropathy, unspecified', 'G62.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (444, 'Antenatal screening', 'Z36', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (445, 'Nonorganic insomnia', 'F51.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (446, 'Keratitis, unspecified', 'H16.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (447, 'Cerebral infarction, unspecified', 'I63.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (448, 'Cellulitis of other parts of limb', 'L03.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (449, 'Enteroviral vesicular stomatitis with exanthem', 'B08.4', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (450, 'Burn of unspecified degree of wrist and hand', 'T23.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (451, 'Tachycardia, unspecified', 'R00.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (452, 'Hyperplasia of prostate', 'N40', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (453, 'Open wound of forearm, part unspecified', 'S51.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (454, 'Calculus of urinary tract in other diseases classified elsewhere', 'N22.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (455, 'Disease of blood and blood-forming organs, unspecified', 'D75.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (456, 'Temporomandibular joint disorders', 'K07.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (457, 'Superficial mycosis, unspecified', 'B36.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (458, 'Unspecified chronic bronchitis', 'J42', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (459, 'Spontaneous abortion - complete or unspecified, without complication', 'O03.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (460, 'Other acute sinusitis', 'J01.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (461, 'Melaena', 'K92.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (462, 'Essential thrombocytosis', 'D75.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (463, 'Dysuria', 'R30.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (464, 'Sprain and strain of other and unspecified parts of hand', 'S63.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (465, 'Chronic viral hepatitis', 'B18', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (466, 'Encounter for attention to dressings, sutures and drains', 'Z48.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (467, 'Tinea unguium', 'B35.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (468, 'Candidiasis of vulva and vagina (N77.1*)', 'B37.3+', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (469, 'Fracture of other and unspecified parts of wrist and hand', 'S62.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (470, 'Keratoconjunctivitis', 'H16.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (471, 'Follow-up examination after treatment for conditions other than', 'Z09', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (472, 'Influenza, virus not identified', 'J11', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (473, 'Fracture of unspecified body region', 'T14.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (474, 'Sprain and strain of finger(s)', 'S63.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (475, 'Gonarthrosis, unspecified', 'M17.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (476, 'Rash and other nonspecific skin eruption', 'R21', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (477, 'Allergic contact dermatitis due to food in contact with skin', 'L23.6', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (478, 'Disorder of lacrimal system, unspecified', 'H04.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (479, 'Psoriasis, unspecified', 'L40.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (480, 'Acute periodontitis', 'K05.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (481, 'Conjunctivitis', 'H10', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (482, 'Sprain and strain of toe(s)', 'S93.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (483, 'Otitis externa in mycoses', 'H62.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (484, 'Foreign body in pharynx', 'T17.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (485, 'Gonococcal infection', 'A54', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (486, 'Foreign body or object entering through skin', 'W45', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (487, 'Dyshidrosis [pompholyx]', 'L30.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (488, 'Nephrotic syndrome - Unspecified', 'N04.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (489, 'Fracture of thumb', 'S62.5', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (490, 'Other and unspecified ovarian cysts', 'N83.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (491, 'Eye, unspecified', 'D31.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (492, 'Multiple open wounds of wrist and hand', 'S61.7', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (493, 'Tuberculous peripheral lymphadenopathy', 'A18.2', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (494, 'Malunion of fracture', 'M84.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (495, 'Cystitis, unspecified', 'N30.9', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (496, 'Migraine with aura [classical migraine]', 'G43.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (497, 'Hyperemesis gravidarum with metabolic disturbance', 'O21.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (498, 'Scrotal varices', 'I86.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (499, 'Influenza with pneumonia, influenza virus identified', 'J10.0', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (500, 'Miliaria crystallina', 'L74.1', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (501, 'Follow-up examination after other treatment for other conditions', 'Z09.8', 1, NULL, NULL);
INSERT INTO `ms_diagnosa` (`id_diagnosa`, `dgn_name`, `dgn_cat`, `dgn_status`, `dgn_insert_dt`, `dgn_insert_by`) VALUES (502, 'Acute bronchiolitis, unspecified', 'J21.9', 1, NULL, NULL);
